config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "nails#index"
  resources :nails do
    resources :comments, only: :create
    collection do
      get 'search'
    end
  end
  resources :users, only: [:show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :nail
  belongs_to :user

  validates :text, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :nail

  validates_uniqueness_of :nail_id, scope: :user_id
end

app/models/nail.rb
class Nail < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :favorites, dependent: :destroy
  has_one_attached :image

  with_options presence: true do
    validates :image
    validates :title
    validates :detail
    validates :thumb
    validates :index_finger
    validates :middle_finger
    validates :ring_finger
    validates :little_finger
  end
  
  def self.search(search)
    if search != ""
      Nail.where('title LIKE(?) OR detail LIKE(?) OR item LIKE(?) OR thumb LIKE(?) OR index_finger LIKE(?) OR ring_finger LIKE(?) OR little_finger LIKE(?)',
                 "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
    else
      Nail.all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :nails
  has_many :comments
  has_many :favorites, dependent: :destroy

  with_options presence: true do
    validates :nickname
    validates :profile
  end

  def already_favorited?(nail)
    self.favorites.exists?(nail_id: nail.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :profile])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create(comment_params)
    @nail = @comment.nail
    @comments = @nail.comments.includes(:user)
    if @comment.save
      redirect_to "/nails/#{@comment.nail.id}"
    else
      render "nails/show"
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, nail_id: params[:nail_id])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @favarite = crrent_user.favorites.create(nail_id: params[:nail_id])
    redirect_back{fallback_location: root_path}
  end

  def destory
    @nail = Nail.find(params[:nail_id])
    @favorite = current_user.favorites.find_by(nail_id: @recipe.id)
    @favorite.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/nails_controller.rb
class NailsController < ApplicationController
  before_action :move_to_index, except: [:index, :show, :search ]
  before_action :set_nail, only: [:show, :edit, :update, :destroy]

  def index
    @nails = Nail.all
  end

  def new
    @nail = Nail.new
  end

  def create
    @nail = Nail.new(nail_params)
    if @nail.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @nail.comments.includes(:user)
  end

  def edit
  end

  def update
    if @nail.update(nail_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @nail.destroy
    redirect_to root_path
  end

  def search
    @nails = Nail.search(params[:keyword])
  end

  private

  def nail_params
    params.require(:nail).permit(:title, :detail, :item, :thumb, :index_finger, :middle_finger, :ring_finger, :little_finger, :image).merge(user_id: current_user.id)    
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end

  def set_nail
    @nail = Nail.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  def show
    @nails = @user.nails
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private
  
  def user_params
    params.require(:user).permit(:nickname, :profile, :email)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/nails_helper.rb
module NailsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Nailrecipe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("logo.png", class: :logo), root_path %>
          </div>
          <% if user_signed_in? %>
            <div class="nav__right">
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: :nav__logout %>
              <%= link_to "New Recipe", new_nail_path, class: :nav__btn %>
            </div>
          <% else %>
            <div class="nav__right">
              <%= link_to "Log in", new_user_session_path, class: :nav__btn %>
              <%= link_to "Sign up", new_user_registration_path, class: :nav__btn %>
            </div>
          <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © Nailrecipe All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/nails/_form.html.erb
<%= form_with model: @nail, local: true do |f|%>

  <div class="field">
    <%= f.label :image, "ネイルデザインの画像" %><br />
    <%= f.file_field :image, id:"nail_image" %>
  </div>


  <div class="field">
    <%= f.label :title, "タイトル" %><br />
    <%= f.text_field :title, id:"nail_title" %>
  </div>

  <div class="field">
    <%= f.label :detail, "デザインの詳細" %><br />
    <%= f.text_area :detail, class: :form__text, id:"nail_detail" %>
  </div>
  <br />

    <div class="field">
    <%= f.label :item, "使用したアイテム" %><br />
    <%= f.text_area :item, class: :form__text, id:"nail_item" %>
  </div>
  <br />

  <div class="field">
    <%= f.label :thumb, "①親指" %><br />
    <%= f.text_area :thumb, class: :form__text, id:"nail_thumb" %>
  </div>

  <div class="field">
    <%= f.label :index_finger, "②人差し指" %><br />
    <%= f.text_area :index_finger, class: :form__text, id:"nail_index_finger" %>
  </div>

  <div class="field">
    <%= f.label :middle_finger, "③中指" %><br />
    <%= f.text_area :middle_finger, class: :form__text, id:"nail_middle_finger" %>
  </div>

  <div class="field">
    <%= f.label :ring_finger, "④薬指" %><br />
    <%= f.text_area :ring_finger, class: :form__text, id:"nail_ring_finger" %>
  </div>

  <div class="field">
    <%= f.label :little_finger, "⑤小指" %><br />
    <%= f.text_area :little_finger, class: :form__text, id:"nail_little_finger" %>
  </div>

  <div class="actions">
    <%= f.submit "投稿する", class: :form__btn  %>
  </div>
<% end %>

app/views/nails/_nail.html.erb
<div class="card">
  <%= link_to image_tag(nail.image, class: :card__img ), nail_path(nail.id) %>
  <div class="card__body">
    <%= link_to nail.title, nail_path(nail.id), class: :card__title%>
    <%= link_to "by #{nail.user.nickname}", user_path(nail.user.id), class: :card__user %>
  </div>
</div>

app/views/nails/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">ネイルレシピ編集</h2>
      <%= render partial:"form", locals:{nail: @nail} %>
    </div>
  </div>
</div>

app/views/nails/index.html.erb
<%= form_with(url: search_nails_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "ネイルデザインを検索する", class: "search-input" %>
  <%= form.submit "検索", class: "form__btn" %>
<% end %>
<br><br>

<main class="main">
  <div class="inner">
    <% if user_signed_in? %>
      <div class="status">
        <%= "Welcome!" %>
        <%= link_to "#{current_user.nickname}", user_path(current_user.id), class: :status__link%>
      </div>
    <% end %>
    <div class="card__wrapper">
      <%= render partial: "nail", collection: @nails %>
    </div>
  </div>
</main>

app/views/nails/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">新しいデザインを投稿しましょう！</h2>
        <%= render "form.html.erb" %>
    </div>
  </div>
</div>

app/views/nails/search.html.erb
<%= form_with(url: search_nails_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
  <%= form.submit "検索", class: "form-btn" %>
<% end %>
<br><br>

<div class="inner">
  <% @nails.each do |nail| %>
    <%= render partial: "nail", locals: { nail: nail } %>
  <% end %>
</div>

app/views/nails/show.html.erb
<main class="main">
  <div class="inner">
    <div class="nail__wrapper">
      <p class="nail__hedding">
        <%= @nail.title %>
      </p>
      <%= link_to "by #{@nail.user.nickname}", user_path(@nail.user.id), class: :nail__user %>
      <% if user_signed_in? && current_user.id == @nail.user_id %>
        <div class="nail__manage">
          <%= link_to "編集する", edit_nail_path, class: :nail__btn %>
          <%= link_to "削除する", nail_path, method: :delete, class: :nail__btn %>
        </div>
      <% end %>
      <div class="nail__image">
        <%= image_tag @nail.image %>
      </div>
      <div class="nail__body">
        <div class="nail__detail">
          <p class="detail__title">デザインの詳細</p>
            <%= safe_join(@nail.detail.split("\n"),tag(:br))%>
          </p>
        </div>
        <br><br>

        <% if user_signed_in? %>
          <div class="nail__item">
            <p class="item__title">使用したアイテム</p>
              <%= safe_join(@nail.item.split("\n"),tag(:br))%>
            </p>
          </div>
          <br><br>

          <div class="nail__fingers">
            <p class="thumb__title">①親指</p>
              <%= safe_join(@nail.thumb.split("\n"),tag(:br))%>
            </p>
            <br>
            <p class="index_finger__title">②人差し指</p>
              <%= safe_join(@nail.index_finger.split("\n"),tag(:br))%>
            </p>
            <br>
            <p class="middle_finger__title">③中指</p>
              <%= safe_join(@nail.middle_finger.split("\n"),tag(:br))%>
            </p>
            <br>
            <p class="ring_finger__title">④薬指</p>
              <%= safe_join(@nail.ring_finger.split("\n"),tag(:br))%>
            </p>
            <br>
            <p class="little_finger__title">⑤小指</p>
              <%= safe_join(@nail.little_finger.split("\n"),tag(:br))%>
            </p>
            <br>
          </div>
        <% end %>
      </div>


      <div class="nail__comments">
        <% if user_signed_in? %>
          <%= form_with model: [@nail, @comment], local: true do |f| %>
            <div class="field">
              <%= f.label :text, "コメント" %><br />
              <%= f.text_field :text, id:"comment_content" %>
            </div>
            <div class="actions">
              <%= f.submit "送信する", class: :form__btn  %>
            </div>
          <% end %>
        <% else %>
          <strong><p>コメントを投稿するにはログインしてください</p></strong>
        <% end %>
        <br>
        <ul class="comments_lists">
        <% @comments.each do |comment| %>
            <li class="comments_list">
              <%= comment.text %>
              <%= link_to "by #{comment.user.nickname}", user_path(comment.user.id), class: :comment_user %>
            </li>
        <% end %>
        </ul>
      </div>
    </div>
  </div>
</main>

app/views/users/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">アカウントを編集</h2>

        <%= form_with model: @user, url: user_path(@user.id), local: true do |f| %>

        <div class="field">
          <%= f.label :email, "メールアドレス" %><br />
          <%= f.email_field :email, id:"user_email", autofocus: true, autocomplete: "email" %>
        </div>

        <div class="field">
          <%= f.label :nickname, "ニックネーム" %><br />
          <%= f.text_field :nickname, id:"user_name" %>
        </div>

        <div class="field">
          <%= f.label :profile, "プロフィール" %><br />
          <%= f.text_area :profile, class: :form__text, id:"user_profile" %>
        </div>
        <br />
        <div class="actions">
          <%= f.submit "編集", class: :form__btn  %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%= "#{@user.nickname}"%>
      </h2>
      <% if user_signed_in? && current_user.id == @user.id %>
        <div class="nail__manage">
          <%= link_to "編集する", edit_user_path(@user.id), class: :nail__btn %>
        </div>
      <% end %>
            <%= safe_join(@user.profile.split("\n"),tag(:br))%>
            <br><br>
      <h2 class="page-heading">
        <%= "#{@user.nickname}'s Nail Gallery"%>
      </h2>
      <div class="user__card">
        <%= render partial: "nails/nail", collection: @nails %>
      </div>
    </div>
  </div>
</div>